### ISSUE TITLE
Typography component in Figma

### ISSUE THREAD

**Issue by vnys** [equinor/design-system-roadmap#2]
To provide our product designers with well-crafted typography options, we are initiating the development of typography components while awaiting the release of typography variables in Figma. These components will lay the foundation for typography tokens. By ensuring consistency and efficiency in our design processes, we empower product designers to create interfaces with carefully curated typography components, including font, size, weight, line height, padding and more.

**Comment by marinalinn** [comment]
This task includes to create the component on Figma and also to test it in different mobile products. Today the component is ready and I am working in the test stage now.

**Comment by marinalinn** [comment]
The typography component was tested with different products and teams.
